name: FileTypeGuard
options:
  bundleIdPrefix: com.filetypeguard
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
localizations:
  - en
  - ja
  - zh-Hans
  - zh-Hant
packages:
  SwiftUIWindowBinder:
    url: https://github.com/happycodelucky/SwiftUIWindowBinder.git
    from: "1.0.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.filetypeguard.mac
    CODE_SIGN_ENTITLEMENTS: FileTypeGuard/App/FileTypeGuard.entitlements
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_STYLE: Automatic
targets:
  FileTypeGuard:
    type: application
    platform: macOS
    sources:
      - FileTypeGuard
    dependencies:
      - package: SwiftUIWindowBinder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.filetypeguard.mac
        CODE_SIGN_ENTITLEMENTS: FileTypeGuard/App/FileTypeGuard.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
    entitlements:
      path: FileTypeGuard/App/FileTypeGuard.entitlements
